"""create_video_tables

Revision ID: 4b8f5d61469f
Revises: 919cf8c06c3c
Create Date: 2026-05-05 10:35:49.456356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8f5d61469f'
down_revision: Union[str, Sequence[str], None] = '919cf8c06c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('master_playlist_file_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], name=op.f('fk_videos_file_id_uploaded_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['master_playlist_file_id'], ['uploaded_files.id'], name=op.f('fk_videos_master_playlist_file_id_uploaded_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_videos_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos')),
    sa.UniqueConstraint('file_id', name=op.f('uq_videos_file_id'))
    )
    op.create_table('video_variants',
    sa.Column('variant_code', sa.Enum('V_2160', 'V_1440', 'V_1080', 'V_720', 'V_480', 'V_360', 'V_240', 'V_144', name='videovariantcode'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('playlist_file_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Enum('MUXING', 'MUXING_FAILED', 'MUXING_NOT_STARTED', 'PROCESSING', 'PROCESSING_FAILED', 'PROCESSING_NOT_STARTED', 'READY', name='videovariantprocessingstate'), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('gop_size', sa.Integer(), nullable=False),
    sa.Column('video_bitrate', sa.Integer(), nullable=False),
    sa.Column('video_max_bitrate', sa.Integer(), nullable=False),
    sa.Column('video_buf_size', sa.Integer(), nullable=False),
    sa.Column('audio_bitrate', sa.Integer(), nullable=False),
    sa.Column('audio_sample_rate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], name=op.f('fk_video_variants_file_id_uploaded_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['playlist_file_id'], ['uploaded_files.id'], name=op.f('fk_video_variants_playlist_file_id_uploaded_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_variants_video_id_videos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('variant_code', 'video_id', name=op.f('pk_video_variants'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_variants')
    op.drop_table('videos')
    # ### end Alembic commands ###
